default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: react_rails_tutorial_development

test:
  <<: *default
  database: react_rails_tutorial_test

production:
  <<: *default
  database: react_rails_tutorial_production
  username: react_rails_tutorial
  password: <%= ENV['RAILS_BASE_DATABASE_PASSWORD'] %>
